### ISSUE TITLE
Cannot connect to WIFI SSID containing single quotation mark

### ISSUE THREAD

**Issue by doody** [UDOOboard/udoo-web-conf#10]
Hi,

I just boot up my udoo neo full board and using web config and trying the "Quick Configuration", when I'm trying to connect to my wifi, it just didn't show up my SSID full name (Doody's AP), and if I select the one of it and save with password, it will failed with wrong password error.

After digging to the code, I found that 

```
var end_pos = arrWifiList[i].indexOf('\'',start_pos);  // This line will cut my SSID name which contain single quotation mark
```

So I try to modify to

```
var end_pos = arrWifiList[i].lastIndexOf('\'');
```

And it works!

I'm not sure if it will cause side effect by using the last single quotation mark as the end position, just want to raise that I have encounter this problem and have this quick fix :)

And another question is that I also found when the frontend is trying to establish the WIFI connection, it use GET to send the SSID and PASSWORD, this will cause wifi password leakage during the first configuration, hope you can fix it in the future.

Thanks and cheers, this web tool is awesome :)

**Comment by fmntf** [comment]
Thank you, I have fixed it in a25bd49aea2eac30e6b2ff5ff56b2973812e9b25
