### ISSUE TITLE
dpkg-buildpackage -b no longer creates udoo-web-conf-modules_0.3.0_all.deb

### ISSUE THREAD

**Issue by Xykon** [UDOOboard/udoo-web-conf#14]
Since the last commit dpkg-buildpackage -b will no longer create udoo-web-conf-modules_0.3.0_all.deb

I traced this down to a change in the control file ./debian/control where Architecture: for Package: udoo-web-conf-modules was changed from all to armhf.

I already tried several ways to tell dpkg-buildpackage to use armhf architecture but don't get the file to be generated. At the moment I just changed the control file back to all but would be nice to know how I can keep generating the packages without having to maintain a local modification.

**Comment by Xykon** [comment]
Well it seems the package is building properly if I create it in a qemu chroot of udoobuntu. I'd still be interested how to properly cross-compile it on an Intel server.

**Comment by ektor5** [comment]
I think you need to tell dpkg-buildpackage (and I hope it tells npm to do the same) to compile for armhf. Npm will then download the right binaries for node.
Actually I'm packaging on UDOO, so I didn't mind to solve this.
