### ISSUE TITLE
Ardublockly not loading examples

### ISSUE THREAD

**Issue by waltervl** [UDOOboard/udoo-web-conf#17]
Just done some basic testing with Ardublockly. It creates, saves  and uploads sketches but it cannot load the examples. After selecting an example a popup appears: Are you sure to proceed? And after clicking OK the ardublockly screen part stays empty. Tested on IE11 on Windows and the chromium browser on the Neo itself. Tested the online Ardublockly demo and that works fine on IE11 on Windows.

**Comment by fmntf** [comment]
Fixed in b70904167fa4e5f502756080525d7ae6f442a582.
@ektor5 please push updated debian packages to the repository.

**Comment by ektor5** [comment]
It'll be done, sir!
