### ISSUE TITLE
Wifi hotspots not loaded despite it being connected via WiFi

### ISSUE THREAD

**Issue by ddewaele** [UDOOboard/udoo-web-conf#3]
Despite the fact that my UDOO is connected to the internet via WiFi

![](https://dl.dropboxusercontent.com/u/13246619/UDOO/neo/Screenshot%202015-12-06%2012.06.58.png)

The dashboard returns an empty list of WiFi hotspots

![](https://dl.dropboxusercontent.com/u/13246619/UDOO/neo/Screenshot%202015-12-06%2012.08.22.png)

```
curl -v  http://192.168.1.117/wifiList
*   Trying 192.168.1.117...
* Connected to 192.168.1.117 (192.168.1.117) port 80 (#0)
> GET /wifiList HTTP/1.1
> Host: 192.168.1.117
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Content-Type: application/json; charset=utf-8
< Content-Length: 149
< ETag: W/"95-WEVjy5EvHQZg9CQNmO1j/w"
< Date: Sun, 06 Dec 2015 11:08:32 GMT
< Connection: keep-alive
< 
* Connection #0 to host 192.168.1.117 left intact
{"wifiListOutput":["SSID                              BSSID               MODE             FREQ       RATE       SIGNAL   SECURITY   ACTIVE  \n",""]}MacBook-Pro:.ssh ddewaele$ 
```

Any ideas ? I configured my Wifi manually by editing `/etc/network/interfaces` and `/etc/wpa_supplicant/wpa_supplicant.conf`.

**Comment by mikelangeloz** [comment]
With your configuration you basically took the network manager out... So not a bug
