### ISSUE TITLE
suggestion: remove node_modules from repository

### ISSUE THREAD

**Issue by carlosperate** [UDOOboard/udoo-web-conf#4]
Just a general suggestion, as the current state on the repository doesn't work after clean clone. I had to remove the folder (well, renamed it and gitignored it) to `npm install` it. This then can be inconvenient to track changes, as it will indicate a ton of deletions due to obvious reasons, even if the folder itself is gitignored as well (so in practice all this does is not report all the new files).

As far as the advantages of keeping it in the repository, this is not longer recommended for close dependency management for things like deployment, https://docs.npmjs.com/misc/faq#should-i-check-my-node-modules-folder-into-git, and it looks like in this specific case the application is being deb packaged, so there should be a pretty replicable set of backups that way.

**Comment by ektor5** [comment]
I agree with that, I made a PR in order to remove them and build a separate package. See #5 for details. 
Please give it a check for a review.

Thanks!
Ek5

**Comment by carlosperate** [comment]
PR looks good to me and has been merged already, good work!
