### ISSUE TITLE
Dashboard not showing all info

### ISSUE THREAD

**Issue by waltervl** [UDOOboard/udoo-web-conf#8]
Dashboard not showing Ethernet connected although ethernet is connected and sudo ifconfig shows it
Internet is connected but not showing 
boardname is default udooneo but not showing
See attached screenshots
I tried it in IE11 and Chrome 47.Chrome is not showing anything!
Chrome view:
![chrome](https://cloud.githubusercontent.com/assets/16327072/11853487/95ae1866-a43e-11e5-9cb6-460f0a5ab921.jpg)
IE11
![dash](https://cloud.githubusercontent.com/assets/16327072/11853392/f723dc80-a43d-11e5-9f87-d15802c1d386.jpg)
lfconfig
![ifconfig](https://cloud.githubusercontent.com/assets/16327072/11853393/f723ed74-a43d-11e5-96ff-0c8fd2ff27cd.jpg)
name configuration but not showing on dashboard
![name](https://cloud.githubusercontent.com/assets/16327072/11853394/f7252afe-a43d-11e5-9026-7cdf3ddfff15.jpg)

**Comment by mikelangeloz** [comment]
Thanks, trying to replicate your issue

**Comment by mikelangeloz** [comment]
Fixed, see https://github.com/UDOOboard/udoo-web-conf/commit/5e9925dc35cab04ea9f8f85deb7f973feb18a002
