### ISSUE TITLE
Arduino editor does not work on Firefox

### ISSUE THREAD

**Issue by carlosperate** [UDOOboard/udoo-web-conf#9]
This is probably already a known issue for the team, but the current editor does not work in Firefox. I cannot input any text, however I can delete text using the backspace or delete keys.

Out of curiosity, is there any reason why something more advanced like the [ACE](https://ace.c9.io/) is not used? Both codebender, and the new Arduino Create use it for their online editors.

**Comment by mikelangeloz** [comment]
No, we were not aware of that...
And thanks for the hint of Ace, I'll look into integrating it (so we'll solve the issue we're having with Firefox...), should not be particularly challenging...

**Comment by fmntf** [comment]
Fixed in b89498a1a833e33f35a56d978d136274701ac1ea
